In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("Lol_matchs.csv").drop(["Unnamed: 0"], axis='columns').drop_duplicates()
df

,Aatrox,Ahri,Akali,Alistar,Amumu,Anivia,Annie,Aphelios,Ashe,Aurelion Sol,...,Yorick.1,Yuumi.1,Zac.1,Zed.1,Ziggs.1,Zilean.1,Zoe.1,Zyra.1,Team1,Team2
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34664,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34665,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
34667,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
34668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [7]:
t1 = [x for x in df.columns[:-2] if ".1" not in x]
t2 = [x for x in df.columns[:-2] if ".1" in x]
t2

['Aatrox.1',
 'Ahri.1',
 'Akali.1',
 'Alistar.1',
 'Amumu.1',
 'Anivia.1',
 'Annie.1',
 'Aphelios.1',
 'Ashe.1',
 'Aurelion Sol.1',
 'Azir.1',
 'Bard.1',
 'Blitzcrank.1',
 'Brand.1',
 'Braum.1',
 'Caitlyn.1',
 'Camille.1',
 'Cassiopeia.1',
 "Cho'Gath.1",
 'Corki.1',
 'Darius.1',
 'Diana.1',
 'Dr. Mundo.1',
 'Draven.1',
 'Ekko.1',
 'Elise.1',
 'Evelynn.1',
 'Ezreal.1',
 'Fiddlesticks.1',
 'Fiora.1',
 'Fizz.1',
 'Galio.1',
 'Gangplank.1',
 'Garen.1',
 'Gnar.1',
 'Gragas.1',
 'Graves.1',
 'Hecarim.1',
 'Heimerdinger.1',
 'Illaoi.1',
 'Irelia.1',
 'Ivern.1',
 'Janna.1',
 'Jarvan IV.1',
 'Jax.1',
 'Jayce.1',
 'Jhin.1',
 'Jinx.1',
 "Kai'Sa.1",
 'Kalista.1',
 'Karma.1',
 'Karthus.1',
 'Kassadin.1',
 'Katarina.1',
 'Kayle.1',
 'Kayn.1',
 'Kennen.1',
 "Kha'Zix.1",
 'Kindred.1',
 'Kled.1',
 "Kog'Maw.1",
 'LeBlanc.1',
 'Lee Sin.1',
 'Leona.1',
 'Lillia.1',
 'Lissandra.1',
 'Lucian.1',
 'Lulu.1',
 'Lux.1',
 'Malphite.1',
 'Malzahar.1',
 'Maokai.1',
 'Master Yi.1',
 'Miss Fortune.1',
 'Mordekaiser.1',
 'Morgana.1',
 'Nami.1',
 'Nasus.1',
 'Nautilus.1',
 'Neeko.1',
 'Nidalee.1',
 'Nocturne.1',
 'Nunu & Willump.1',
 'Olaf.1',
 'Orianna.1',
 'Ornn.1',
 'Pantheon.1',
 'Poppy.1',
 'Pyke.1',
 'Qiyana.1',
 'Quinn.1',
 'Rakan.1',
 'Rammus.1',
 "Rek'Sai.1",
 'Renekton.1',
 'Rengar.1',
 'Riven.1',
 'Rumble.1',
 'Ryze.1',
 'Sejuani.1',
 'Senna.1',
 'Sett.1',
 'Shaco.1',
 'Shen.1',
 'Shyvana.1',
 'Singed.1',
 'Sion.1',
 'Sivir.1',
 'Skarner.1',
 'Sona.1',
 'Soraka.1',
 'Swain.1',
 'Sylas.1',
 'Syndra.1',
 'Tahm Kench.1',
 'Taliyah.1',
 'Talon.1',
 'Taric.1',
 'Teemo.1',
 'Thresh.1',
 'Tristana.1',
 'Trundle.1',
 'Tryndamere.1',
 'Twisted Fate.1',
 'Twitch.1',
 'Udyr.1',
 'Urgot.1',
 'Varus.1',
 'Vayne.1',
 'Veigar.1',
 "Vel'Koz.1",
 'Vi.1',
 'Viktor.1',
 'Vladimir.1',
 'Volibear.1',
 'Warwick.1',
 'Wukong.1',
 'Xayah.1',
 'Xerath.1',
 'Xin Zhao.1',
 'Yasuo.1',
 'Yone.1',
 'Yorick.1',
 'Yuumi.1',
 'Zac.1',
 'Zed.1',
 'Ziggs.1',
 'Zilean.1',
 'Zoe.1',
 'Zyra.1']